#!/usr/bin/env python3
"""Build _i18n_triples.json with complete fr/zh/rw maps for all 332 English strings."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent

KEEP = {
    "Urumuri Transport",
    "Urumuri Food",
    "Urumuri Courier",
    "WhatsApp",
    "© 2026 Urumuri",
    "Kigali Innovation District, Kigali, Rwanda",
    "+250 7XX XXX XXX",
    "your.email@example.com",
    "24/7",
    "200+",
    "7 menu items leading revenue.",
    "Thank you! 🎉",
}


def load_rw_seed() -> dict[str, str]:
    return json.loads((ROOT / "_rw_seed.json").read_text(encoding="utf-8"))


# French overrides (professional Rwanda mobility context)
FR: dict[str, str] = {
    "Home": "Accueil",
    "Merchants": "Commerçants",
    "Drivers": "Chauffeurs",
    "About Us": "À propos",
    "Contact": "Contact",
    "Safety": "Sécurité",
    "Reviews": "Avis",
    "Offers": "Offres",
    "How it Works": "Comment ça marche",
    "Rwanda's next-generation mobility platform for transport, food, courier and merchant intelligence.": "Plateforme de mobilité nouvelle génération au Rwanda pour le transport, la restauration, la livraison et l'intelligence commerciale.",
    "Fast deliveries in Kigali and nearby districts.": "Livraisons rapides à Kigali et dans les districts voisins.",
    "Legal": "Mentions légales",
    "Company": "Entreprise",
    "Support": "Assistance",
    "Privacy Policy": "Politique de confidentialité",
    "Terms & Conditions": "Conditions générales",
    "Cookie Policy": "Politique de cookies",
    "Driver Terms": "Conditions chauffeurs",
    "Merchant Terms": "Conditions commerçants",
    "Careers": "Carrières",
    "Business Inquiries": "Demandes commerciales",
    "FAQs": "FAQ",
    "Downloads": "Téléchargements",
    "How it works": "Comment ça marche",
    "Leave a Review": "Laisser un avis",
    "Toggle light and dark mode": "Basculer entre mode clair et sombre",
    "Choose language": "Choisir la langue",
    "Operations intelligence": "Intelligence opérationnelle",
    "Daily fleet deployments": "Déploiements quotidiens de la flotte",
    "Trusted": "Fiable",
    "Across Kigali and nearby districts": "À Kigali et dans les districts voisins",
    "Safe everyday rides with premium safety equipment and intelligent dispatch.": "Trajets quotidiens sûrs avec équipement de sécurité premium et dispatch intelligent.",
    "Explore transport": "Découvrir le transport",
    "Restaurant and grocery delivery designed for fast, reliable urban living.": "Livraison de restaurants et d'épicerie conçue pour une vie urbaine rapide et fiable.",
    "Explore food": "Découvrir la restauration",
    "Professional package delivery with secure handling and same-day options.": "Livraison professionnelle de colis avec manutention sécurisée et options le jour même.",
    "Explore courier": "Découvrir la livraison",
    "Next-generation mobility for Rwanda": "Mobilité nouvelle génération pour le Rwanda",
    "Moving Rwanda Forward.": "Faire avancer le Rwanda.",
    "Transportation. Food. Courier. Built around people, powered by intelligent logistics and premium experiences.": "Transport. Restauration. Livraison. Centré sur les personnes, propulsé par une logistique intelligente et des expériences premium.",
    "Download App": "Télécharger l'application",
    "Become a Partner": "Devenir partenaire",
    "Urumuri ecosystem": "Écosystème Urumuri",
    "Electric rides": "Trajets électriques",
    "Courier & food flow": "Flux livraison et restauration",
    "Smart logistics": "Logistique intelligente",
    "Ecosystem highlights": "Points forts de l'écosystème",
    "One platform for transport, food, courier and business intelligence.": "Une plateforme pour le transport, la restauration, la livraison et l'intelligence commerciale.",
    "Premium merchant intelligence": "Intelligence commerciale premium",
    "Actionable analytics, inventory forecasting, revenue insights and demand signals for growing businesses.": "Analyses exploitables, prévisions de stock, insights sur les revenus et signaux de demande pour les entreprises en croissance.",
    "Empowered drivers": "Chauffeurs autonomes",
    "Flexible income, professional training and electric motorcycles for a safer, modern fleet.": "Revenus flexibles, formation professionnelle et motos électriques pour une flotte plus sûre et moderne.",
    "Premium capabilities": "Capacités premium",
    "Built on data, safety and seamless service.": "Fondé sur les données, la sécurité et un service fluide.",
    "Smart dispatch": "Dispatch intelligent",
    "Real-time routing ensures every ride and delivery moves faster and safer.": "Le routage en temps réel garantit des trajets et livraisons plus rapides et plus sûrs.",
    "Dynamic pricing": "Tarification dynamique",
    "Transparent pricing that considers distance, urgency, traffic and customer value.": "Tarification transparente tenant compte de la distance, de l'urgence, du trafic et de la valeur client.",
    "Merchant partnerships": "Partenariats commerçants",
    "Tools designed to help businesses track performance, manage inventory and attract demand.": "Outils conçus pour suivre les performances, gérer les stocks et attirer la demande.",
    "Community care": "Engagement communautaire",
    "Discount programs for students and Umuganda participants support Rwanda's shared future.": "Des réductions pour les étudiants et les participants à l'Umuganda soutiennent l'avenir commun du Rwanda.",
    "Partner with Urumuri": "Partenariat avec Urumuri",
    "Rwanda's next transport ecosystem starts here.": "Le prochain écosystème de transport du Rwanda commence ici.",
    "Technology, safety and premium service designed to move riders, businesses and packages with confidence.": "Technologie, sécurité et service premium pour déplacer passagers, entreprises et colis en toute confiance.",
    "Start your journey": "Commencer votre parcours",
    "Flagship service": "Service phare",
    "Every ride is designed for safety, rider comfort and modern city mobility. Our service is Rwanda's premium choice for everyday travel.": "Chaque trajet est conçu pour la sécurité, le confort et la mobilité urbaine moderne. Notre service est le choix premium du Rwanda pour les déplacements quotidiens.",
    "Book a Ride": "Réserver un trajet",
    "Become a Driver": "Devenir chauffeur",
    "Safe journeys": "Trajets sûrs",
    "Electric bikes with premium safety habits": "Motos électriques avec des habitudes de sécurité premium",
    "Safe Riding Experience": "Expérience de conduite sécurisée",
    "Visibility, comfort and electric power for every rider.": "Visibilité, confort et motorisation électrique pour chaque conducteur.",
    "Premium helmets": "Casques premium",
    "Every rider and passenger receives certified helmets for safer journeys across Kigali.": "Chaque conducteur et passager reçoit un casque certifié pour des trajets plus sûrs à Kigali.",
    "Rain-ready comfort": "Confort par tous les temps",
    "Raincoats and protected seating keep passengers dry and secure in any weather.": "Imperméables et sièges protégés gardent les passagers au sec et en sécurité par tous les temps.",
    "Reflective safety gear": "Équipement de sécurité réfléchissant",
    "High-visibility branding and reflective trims improve safety on evening rides.": "Marquage haute visibilité et bandes réfléchissantes améliorent la sécurité en soirée.",
    "Electric motorcycles": "Motos électriques",
    "Our fleet is modern, efficient and built for lower emissions while keeping passengers comfortable.": "Notre flotte est moderne, efficace et conçue pour réduire les émissions tout en assurant le confort des passagers.",
    "Passenger-first travel": "Voyage centré sur le passager",
    "Every trip is guided by seat comfort, clear communication and customer-focused service.": "Chaque trajet est guidé par le confort, une communication claire et un service centré sur le client.",
    "Student Transportation Program": "Programme de transport étudiant",
    "Supporting students with safer, more affordable access to campus.": "Soutenir les étudiants avec un accès plus sûr et abordable au campus.",
    "Discounted rides": "Trajets à tarif réduit",
    "Students access lower fares so they can travel reliably between campus, internships and home.": "Les étudiants bénéficient de tarifs réduits pour se déplacer entre le campus, les stages et leur domicile.",
    "Study-first mobility": "Mobilité au service des études",
    "Focused on making transportation one less worry so students can dedicate time to learning.": "Pour que le transport ne soit plus une préoccupation et que les étudiants puissent se consacrer à leurs études.",
    "Youth empowerment": "Autonomisation des jeunes",
    "Program support includes mentorship, work opportunities and community partnerships.": "Le programme inclut mentorat, opportunités d'emploi et partenariats communautaires.",
    "Community Support": "Soutien communautaire",
    "Umuganda discounts for riders who help build Rwanda.": "Réductions Umuganda pour les passagers qui contribuent à construire le Rwanda.",
    "Passengers participating in Umuganda are rewarded with discounted rides, making mobility part of Rwanda's shared growth.": "Les passagers participant à l'Umuganda sont récompensés par des trajets à tarif réduit, intégrant la mobilité à la croissance commune du Rwanda.",
    "Learn More": "En savoir plus",
    "Food logistics": "Logistique alimentaire",
    "Restaurant meals, groceries and daily essentials delivered with speed, safety and premium care.": "Repas de restaurant, courses et essentiels du quotidien livrés avec rapidité, sécurité et soin premium.",
    "Order Now": "Commander maintenant",
    "Partner with Us": "Devenir partenaire",
    "Seamless delivery": "Livraison fluide",
    "Fresh meals and groceries bringing convenience home.": "Repas frais et courses apportant la commodité à domicile.",
    "Food services": "Services alimentaires",
    "Restaurant, grocery and buy-for-me delivery in one premium experience.": "Restaurant, épicerie et achats pour vous dans une expérience premium unique.",
    "Restaurant Delivery": "Livraison restaurant",
    "From local favorites to premium dining, your meal arrives warm, fast and carefully handled.": "Des adresses locales aux restaurants premium, votre repas arrive chaud, rapidement et soigneusement transporté.",
    "Grocery Delivery": "Livraison d'épicerie",
    "Fresh produce, pantry staples and household essentials ready when you need them most.": "Produits frais, denrées de base et essentiels du foyer disponibles quand vous en avez besoin.",
    "Buy For Me": "Acheter pour moi",
    "Too busy to shop? Our team picks, buys and delivers items on your behalf with trusted accuracy.": "Pas le temps de faire les courses ? Notre équipe sélectionne, achète et livre pour vous avec précision.",
    "At work": "Au bureau",
    "Office meals and meetings stay on schedule with dependable delivery and live tracking.": "Repas de bureau et réunions respectent les horaires grâce à une livraison fiable et un suivi en direct.",
    "At home": "À la maison",
    "Groceries and essentials arrive safely so families can focus on the day ahead.": "Courses et essentiels arrivent en toute sécurité pour que les familles se concentrent sur leur journée.",
    "Everyday support": "Assistance au quotidien",
    "Built for busy lives, flexible schedules and modern urban demand.": "Conçu pour les vies actives, les horaires flexibles et la demande urbaine moderne.",
    "Fast fulfillment": "Exécution rapide",
    "Real-time order routing and trained couriers keep deliveries on time.": "Routage des commandes en temps réel et livreurs formés assurent des livraisons ponctuelles.",
    "Secure handoff": "Remise sécurisée",
    "Careful packaging and safe delivery protect every order from pickup to doorstep.": "Emballage soigné et livraison sécurisée protègent chaque commande du retrait à la porte.",
    "Smart support": "Assistance intelligente",
    "Customer service and visibility keep every order in control from start to finish.": "Service client et visibilité gardent chaque commande sous contrôle du début à la fin.",
    "Food made easier": "La restauration simplifiée",
    "Order meals, groceries and essentials with a premium delivery experience.": "Commandez repas, courses et essentiels avec une expérience de livraison premium.",
    "Every request is handled by trained riders, from kitchen to customer.": "Chaque demande est traitée par des livreurs formés, de la cuisine au client.",
    "Place an Order": "Passer une commande",
    "Courier excellence": "Excellence en livraison",
    "Professional package delivery for documents, business parcels and personal shipments with secure handling and same-day options.": "Livraison professionnelle de documents, colis professionnels et envois personnels avec manutention sécurisée et options le jour même.",
    "Request Courier": "Demander un coursier",
    "Merchant Solutions": "Solutions commerçants",
    "Secure delivery": "Livraison sécurisée",
    "Protected packaging, trained riders and end-to-end visibility.": "Emballage protégé, livreurs formés et visibilité de bout en bout.",
    "Courier services": "Services de livraison",
    "Document, business and personal deliveries executed with precision.": "Livraisons de documents, professionnelles et personnelles exécutées avec précision.",
    "Document Delivery": "Livraison de documents",
    "Urgent papers delivered securely to offices, campuses and partners across Kigali.": "Documents urgents livrés en toute sécurité aux bureaux, campus et partenaires à Kigali.",
    "Business Parcels": "Colis professionnels",
    "Reliable handling for invoices, retail packages and B2B shipments.": "Manutention fiable pour factures, colis retail et expéditions B2B.",
    "Personal Deliveries": "Livraisons personnelles",
    "Carefully managed handoffs for gifts, essentials and sensitive items.": "Remises soigneusement gérées pour cadeaux, essentiels et articles sensibles.",
    "Same-Day Delivery": "Livraison le jour même",
    "Choose premium speed for time-sensitive deliveries with guaranteed alignment from pickup to drop-off.": "Choisissez la vitesse premium pour les livraisons urgentes avec coordination garantie du retrait à la livraison.",
    "Tracking & handling": "Suivi et manutention",
    "Real-time visibility helps you monitor progress, while secure packaging protects every item.": "La visibilité en temps réel permet de suivre la progression, tandis que l'emballage sécurisé protège chaque article.",
    "Professional service": "Service professionnel",
    "Trained riders, secure processes and package protection at every step.": "Livreurs formés, processus sécurisés et protection des colis à chaque étape.",
    "Package protection": "Protection des colis",
    "Designed for fragile items, valuable shipments and demanding business needs.": "Conçu pour les articles fragiles, envois de valeur et besoins professionnels exigeants.",
    "Professional training": "Formation professionnelle",
    "Courier teams receive service, safety and secure handling training before every route.": "Les équipes de livraison reçoivent une formation service, sécurité et manutention avant chaque tournée.",
    "Workflow clarity": "Clarté du processus",
    "Order creation, picking, dispatch and delivery updates keep every shipment accountable.": "Création de commande, préparation, dispatch et mises à jour de livraison assurent la traçabilité de chaque envoi.",
    "Ready to ship": "Prêt à expédier",
    "Move documents and packages with a courier service that feels modern, reliable and secure.": "Expédiez documents et colis avec un service de livraison moderne, fiable et sécurisé.",
    "Schedule Delivery": "Planifier une livraison",
    "Merchant intelligence": "Intelligence commerciale",
    "Urumuri Merchants": "Urumuri Merchants",
    "A premium dashboard for smart inventory, revenue tracking and AI-powered decisions tailored for growing businesses.": "Tableau de bord premium pour la gestion intelligente des stocks, le suivi des revenus et des décisions assistées par IA pour les entreprises en croissance.",
    "Request Access": "Demander l'accès",
    "Sales analytics": "Analyses des ventes",
    "Live metrics, demand forecasting and inventory alerts for your business.": "Métriques en direct, prévisions de demande et alertes de stock pour votre entreprise.",
    "Dashboard preview": "Aperçu du tableau de bord",
    "Modern sales analytics built for merchants and operators.": "Analyses de ventes modernes conçues pour commerçants et opérateurs.",
    "Sales Today": "Ventes aujourd'hui",
    "Sales This Week": "Ventes cette semaine",
    "Sales This Month": "Ventes ce mois-ci",
    "Average Order Value": "Valeur moyenne des commandes",
    "Orders": "Commandes",
    "Best Sellers": "Meilleures ventes",
    "Revenue analytics": "Analyses des revenus",
    "Monthly, weekly and daily graphs help you spot peaks, plan stock and optimise promotions.": "Graphiques mensuels, hebdomadaires et quotidiens pour repérer les pics, planifier les stocks et optimiser les promotions.",
    "Product performance": "Performance des produits",
    "Track top performing and slow moving products to improve inventory decisions.": "Suivez les produits performants et les articles à rotation lente pour améliorer vos décisions de stock.",
    "Insights that answer the questions every business needs.": "Des insights qui répondent aux questions essentielles de chaque entreprise.",
    "What sells most?": "Qu'est-ce qui se vend le plus ?",
    "Identify your highest performing dishes and restock with confidence.": "Identifiez vos plats les plus performants et réapprovisionnez en toute confiance.",
    "When to hire?": "Quand recruter ?",
    "See peak demand windows and staffing opportunities in real time.": "Visualisez les pics de demande et les opportunités de recrutement en temps réel.",
    "Which inventory to restock?": "Quel stock réapprovisionner ?",
    "Alerts for slowing items and suggested reorder levels keep shelves full.": "Alertes sur les articles en baisse et niveaux de réapprovisionnement suggérés pour garder les rayons pleins.",
    "Highest revenue items": "Articles à plus fort revenu",
    "Discover the menu and product combinations generating the greatest return.": "Découvrez les combinaisons menu et produits générant le meilleur retour.",
    "Future platform": "Plateforme future",
    "Upcoming merchant advertising tools": "Outils publicitaires commerçants à venir",
    "Grow visibility inside the Urumuri ecosystem with targeted promotions for customers on route.": "Augmentez votre visibilité dans l'écosystème Urumuri avec des promotions ciblées pour les clients en déplacement.",
    "Coming Soon": "Bientôt disponible",
    "Dynamic Pricing": "Tarification dynamique",
    "Fair and transparent pricing across transport and delivery services.": "Tarification juste et transparente pour le transport et la livraison.",
    "Transport pricing remains simple and predictable. Delivery fees may vary based on traffic, distance, time of day and urgency.": "Les tarifs de transport restent simples et prévisibles. Les frais de livraison peuvent varier selon le trafic, la distance, l'heure et l'urgence.",
    "Traffic aware": "Adapté au trafic",
    "Pricing follows real route conditions for better service value.": "La tarification suit les conditions réelles de trajet pour une meilleure valeur de service.",
    "Distance-based": "Basé sur la distance",
    "Transparent fees that reflect the true journey required.": "Frais transparents reflétant le trajet réel nécessaire.",
    "Urgency tiers": "Niveaux d'urgence",
    "Customers choose the speed they need without surprise costs.": "Les clients choisissent la vitesse souhaitée sans coûts surprises.",
    "Driver recruitment": "Recrutement de chauffeurs",
    "Join Urumuri": "Rejoindre Urumuri",
    "Earn flexible income while driving with modern equipment, safety training and support for growth.": "Gagnez un revenu flexible en conduisant avec un équipement moderne, une formation sécurité et un accompagnement à la croissance.",
    "Apply Now": "Postuler maintenant",
    "Driver Benefits": "Avantages chauffeurs",
    "Flexible income": "Revenus flexibles",
    "Electric vehicles and professional gear designed for modern drivers.": "Véhicules électriques et équipement professionnel conçus pour les chauffeurs modernes.",
    "Driver benefits": "Avantages chauffeurs",
    "Flexible work, professional training and a safer fleet for every partner.": "Travail flexible, formation professionnelle et une flotte plus sûre pour chaque partenaire.",
    "Drive on your schedule, choose your routes and get rewarded for consistent service.": "Conduisez selon votre emploi du temps, choisissez vos itinéraires et soyez récompensé pour un service constant.",
    "Professional equipment": "Équipement professionnel",
    "Premium helmets, reflective gear and electric motorcycles are provided for every driver.": "Casques premium, équipement réfléchissant et motos électriques fournis à chaque chauffeur.",
    "Safety training": "Formation sécurité",
    "Structured onboarding ensures every rider is prepared for safe performance on the road.": "Un onboarding structuré garantit que chaque conducteur est prêt pour une conduite sûre.",
    "Growth opportunities": "Opportunités de croissance",
    "Advance into mentor roles, fleet leadership and specialised delivery services.": "Évoluez vers des rôles de mentor, de leadership de flotte et de services de livraison spécialisés.",
    "Ride modern vehicles with better efficiency, reliability and comfort for every trip.": "Conduisez des véhicules modernes plus efficaces, fiables et confortables à chaque trajet.",
    "Safety support": "Assistance sécurité",
    "Emergency response, insurance-ready procedures and rider-first safety systems.": "Intervention d'urgence, procédures prêtes pour l'assurance et systèmes de sécurité centrés sur le conducteur.",
    "Partner with purpose": "Partenariat engagé",
    "Build a professional driving career with Rwanda's next-generation mobility platform.": "Construisez une carrière de conduite professionnelle avec la plateforme de mobilité nouvelle génération du Rwanda.",
    "Start application": "Commencer la candidature",
    "Our story": "Notre histoire",
    "About Urumuri": "À propos d'Urumuri",
    "We are Rwanda's intelligent mobility ecosystem, designed to move people, packages and businesses forward with safety and innovation.": "Nous sommes l'écosystème de mobilité intelligent du Rwanda, conçu pour faire avancer personnes, colis et entreprises avec sécurité et innovation.",
    "Contact Us": "Nous contacter",
    "Join Our Team": "Rejoindre notre équipe",
    "Mission driven": "Guidés par une mission",
    "Innovation, safety and community at the core of every experience.": "Innovation, sécurité et communauté au cœur de chaque expérience.",
    "Mission": "Mission",
    "To create Rwanda's leading mobility ecosystem that combines transportation, food delivery, courier services and merchant intelligence in one premium platform.": "Créer l'écosystème de mobilité leader du Rwanda combinant transport, livraison alimentaire, services de coursier et intelligence commerciale sur une plateforme premium.",
    "Vision": "Vision",
    "To redefine urban movement across Africa through technology, safety and community-minded service.": "Redéfinir la mobilité urbaine en Afrique grâce à la technologie, la sécurité et un service axé sur la communauté.",
    "Core values": "Valeurs fondamentales",
    "Innovation, safety, community, integrity and sustainability guide every decision.": "Innovation, sécurité, communauté, intégrité et durabilité guident chaque décision.",
    "Innovation": "Innovation",
    "We build smarter mobility with data-driven services and intelligent platform design.": "Nous construisons une mobilité plus intelligente avec des services basés sur les données et une plateforme intelligente.",
    "Passenger protection, rider training and secure delivery are never optional.": "La protection des passagers, la formation des conducteurs et la livraison sécurisée ne sont jamais optionnelles.",
    "Community": "Communauté",
    "Discount programs, Umuganda support and youth empowerment help us grow together.": "Programmes de réduction, soutien à l'Umuganda et autonomisation des jeunes nous aident à grandir ensemble.",
    "Sustainability": "Durabilité",
    "Electric motorcycles, efficient routing and responsible operations reduce our footprint.": "Motos électriques, routage efficace et opérations responsables réduisent notre empreinte.",
    "Impact": "Impact",
    "Building a future-ready transportation platform for urban communities.": "Construire une plateforme de transport prête pour l'avenir des communautés urbaines.",
    "Urumuri invests in people, local businesses and safer streets through premium service and strategic partnerships.": "Urumuri investit dans les personnes, les entreprises locales et des rues plus sûres grâce à un service premium et des partenariats stratégiques.",
    "Local growth": "Croissance locale",
    "Supporting merchants and drivers with tools that grow businesses across Kigali.": "Soutenir commerçants et chauffeurs avec des outils qui font croître les entreprises à Kigali.",
    "Programs for students and young drivers help build skills and economic opportunity.": "Des programmes pour étudiants et jeunes chauffeurs développent compétences et opportunités économiques.",
    "Smart growth": "Croissance intelligente",
    "Data, analytics and automation keep the platform adaptive, stable and future ready.": "Données, analyses et automatisation maintiennent la plateforme adaptable, stable et prête pour l'avenir.",
    "Get in touch with Urumuri": "Contactez Urumuri",
    "Connect with our team for partnerships, support, driver applications and merchant services.": "Contactez notre équipe pour partenariats, assistance, candidatures chauffeurs et services commerçants.",
    "Email Us": "Nous envoyer un e-mail",
    "Support ready": "Assistance disponible",
    "Modern contact tools for business, drivers and customers.": "Outils de contact modernes pour entreprises, chauffeurs et clients.",
    "Office location": "Adresse du bureau",
    "Phone": "Téléphone",
    "Email": "E-mail",
    "Reach us": "Nous joindre",
    "Business inquiries, support or driver applications... we're here to help.": "Demandes commerciales, assistance ou candidatures chauffeurs... nous sommes là pour vous aider.",
    "Business inquiries": "Demandes commerciales",
    "Partner with Urumuri for merchant services, advertising and logistics collaboration.": "Partenariat avec Urumuri pour services commerçants, publicité et collaboration logistique.",
    "Driver support": "Assistance chauffeurs",
    "Apply to join our fleet or ask about rider training and equipment.": "Postulez pour rejoindre notre flotte ou renseignez-vous sur la formation et l'équipement.",
    "Customer support": "Assistance client",
    "Get help with orders, deliveries and platform questions.": "Obtenez de l'aide pour commandes, livraisons et questions sur la plateforme.",
    "Press & media": "Presse et médias",
    "Connect with Urumuri for announcements and media partnerships.": "Contactez Urumuri pour annonces et partenariats médias.",
    "Stay connected": "Restez connectés",
    "Follow our journey as Rwanda's intelligent mobility ecosystem grows.": "Suivez notre parcours alors que l'écosystème de mobilité intelligent du Rwanda se développe.",
    "Write to us": "Écrivez-nous",
    "Safety first": "La sécurité d'abord",
    "Urumuri Safety": "Urumuri Safety",
    "From passengers to packages, safety is the foundation of every journey on the Urumuri network.": "Des passagers aux colis, la sécurité est le fondement de chaque trajet sur le réseau Urumuri.",
    "Contact Support": "Contacter l'assistance",
    "Driver Training": "Formation chauffeurs",
    "Protection powered": "Protection renforcée",
    "Premium safety equipment, rider training and emergency support built in.": "Équipement de sécurité premium, formation des conducteurs et assistance d'urgence intégrés.",
    "Passenger protection": "Protection des passagers",
    "Premium helmets, reflective gear and emergency-ready support.": "Casques premium, équipement réfléchissant et assistance d'urgence prête.",
    "High quality helmets are available to every rider and passenger on every trip.": "Des casques de haute qualité sont disponibles pour chaque conducteur et passager à chaque trajet.",
    "Reflective safety": "Sécurité réfléchissante",
    "High-visibility gear improves awareness on busy city roads and at night.": "L'équipement haute visibilité améliore la perception sur les routes urbaines chargées et la nuit.",
    "Electric visibility": "Visibilité électrique",
    "Our electric bikes feature bold branding and lighting for safer travel in traffic.": "Nos motos électriques arborent un marquage visible et un éclairage pour une conduite plus sûre dans le trafic.",
    "Professional rider training": "Formation professionnelle des conducteurs",
    "Structured programs teach safe handling, customer care and route discipline for every driver.": "Des programmes structurés enseignent la conduite sûre, le service client et la discipline d'itinéraire à chaque conducteur.",
    "Secure packaging, protective seals and careful handoffs keep deliveries intact.": "Emballage sécurisé, scellés de protection et remises soigneuses préservent l'intégrité des livraisons.",
    "Emergency readiness": "Préparation aux urgences",
    "Support systems and future-ready insurance for every trip.": "Systèmes d'assistance et assurance prête pour l'avenir à chaque trajet.",
    "Emergency support, rider check-ins and insurance preparation are part of our long-term service plan.": "Assistance d'urgence, vérifications des conducteurs et préparation assurance font partie de notre plan de service à long terme.",
    "Emergency support": "Assistance d'urgence",
    "Rapid response processes help keep riders and passengers safe on the road.": "Des processus de réponse rapide aident à maintenir la sécurité des conducteurs et passagers sur la route.",
    "Package care": "Soin des colis",
    "Every courier item is handled with care from pickup to final handoff.": "Chaque colis est traité avec soin du retrait à la remise finale.",
    "Insurance ready": "Prêt pour l'assurance",
    "Future insurance integration ensures a safer platform for every customer.": "L'intégration future de l'assurance garantit une plateforme plus sûre pour chaque client.",
    "Our commitment": "Notre engagement",
    "Safety is the promise that shapes every part of the Urumuri platform.": "La sécurité est la promesse qui façonne chaque aspect de la plateforme Urumuri.",
    "Speak with us": "Parlez avec nous",
    "Share your experience": "Partagez votre expérience",
    "Help us improve your delivery experience by sharing your feedback": "Aidez-nous à améliorer votre expérience de livraison en partageant vos commentaires",
    "Your review has been submitted successfully. We appreciate your feedback!": "Votre avis a été soumis avec succès. Nous apprécions vos commentaires !",
    "Your Name *": "Votre nom *",
    "Enter your full name": "Entrez votre nom complet",
    "Email Address *": "Adresse e-mail *",
    "Phone Number": "Numéro de téléphone",
    "Service Type *": "Type de service *",
    "Select a service": "Sélectionnez un service",
    "Food Delivery": "Livraison alimentaire",
    "Pharmacy Delivery": "Livraison pharmacie",
    "Courier Services": "Services de livraison",
    "Buy for Me Services": "Services Acheter pour moi",
    "Other": "Autre",
    "Rating *": "Note *",
    "Select rating": "Sélectionnez une note",
    "Poor": "Médiocre",
    "Fair": "Passable",
    "Good": "Bien",
    "Very Good": "Très bien",
    "Excellent": "Excellent",
    "Your Review *": "Votre avis *",
    "Share your experience with Urumuri...": "Partagez votre expérience avec Urumuri...",
    "Submit Review": "Soumettre l'avis",
    "Back Home": "Retour à l'accueil",
}

# Load extended ZH and RW from companion files if present
ZH_PATH = ROOT / "_zh_map.json"
RW_EXTRA_PATH = ROOT / "_rw_extra.json"


def main() -> None:
    en_strings = json.loads((ROOT / "_en_strings.json").read_text(encoding="utf-8"))
    fr_seed = json.loads((ROOT / "_fr_seed.json").read_text(encoding="utf-8"))
    rw_seed = load_rw_seed()

    fr = {**fr_seed, **FR}
    zh = json.loads(ZH_PATH.read_text(encoding="utf-8")) if ZH_PATH.exists() else {}
    rw_extra = json.loads(RW_EXTRA_PATH.read_text(encoding="utf-8")) if RW_EXTRA_PATH.exists() else {}
    rw = {**rw_seed, **rw_extra}

    for s in KEEP:
        fr[s] = s
        zh[s] = s
        rw[s] = s

    for s in en_strings:
        fr.setdefault(s, s)
        zh.setdefault(s, s)
        rw.setdefault(s, s)

    triples = {"fr": fr, "zh": zh, "rw": rw}
    for lang in ("fr", "zh", "rw"):
        missing = [s for s in en_strings if s not in triples[lang]]
        if missing:
            raise SystemExit(f"{lang} missing keys: {missing[:5]}")
    out = ROOT / "_i18n_triples.json"
    out.write_text(json.dumps(triples, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
