#!/usr/bin/env python3
"""Build complete i18n_data.py with en, fr, hi, zh, rw translations."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "i18n_data.py"


def deep_translate(obj, mapping: dict[str, str]):
    if isinstance(obj, dict):
        return {k: deep_translate(v, mapping) for k, v in obj.items()}
    if isinstance(obj, list):
        return [deep_translate(v, mapping) for v in obj]
    if isinstance(obj, str):
        return mapping.get(obj, obj)
    return obj


def load_en() -> dict:
    ns: dict = {}
    exec((ROOT / "i18n_data.py").read_text(encoding="utf-8"), ns)
    return ns["TRANSLATIONS"]["en"]


def flatten_strings(obj, out: set[str] | None = None) -> set[str]:
    out = out or set()
    if isinstance(obj, dict):
        for v in obj.values():
            flatten_strings(v, out)
    elif isinstance(obj, list):
        for v in obj:
            flatten_strings(v, out)
    elif isinstance(obj, str):
        out.add(obj)
    return out


def main() -> None:
    from lang_maps import FR_MAP, HI_MAP, ZH_MAP, RW_MAP

    en = load_en()
    translations = {
        "en": en,
        "fr": deep_translate(en, FR_MAP),
        "hi": deep_translate(en, HI_MAP),
        "zh": deep_translate(en, ZH_MAP),
        "rw": deep_translate(en, RW_MAP),
    }

    for lang, data in translations.items():
        if lang == "en":
            continue
        en_strings = flatten_strings(en)
        lang_strings = flatten_strings(data)
        untranslated = sorted(s for s in en_strings if s in lang_strings and s not in {"Urumuri", "URUMURI", "Urumuri Transport", "Urumuri Food", "Urumuri Courier", "Urumuri Merchants", "Urumuri Safety", "WhatsApp", "© 2026 Urumuri", "24/7", "200+", "Trusted", "Kigali Innovation District, Kigali, Rwanda", "+250 7XX XXX XXX", "your.email@example.com", "7 menu items leading revenue.", "Thank you! 🎉"})
        if len(untranslated) > 30:
            print(f"Warning: {lang} has {len(untranslated)} possibly untranslated strings")

    OUT.write_text(
        "# Auto-generated by make_i18n.py\n"
        "TRANSLATIONS = "
        + json.dumps(translations, ensure_ascii=False, indent=2)
        + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT} with languages: {', '.join(translations)}")


if __name__ == "__main__":
    main()
